name: Check Vulkan Headers Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-updates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Check for Vulkan-Headers updates
        id: check-update
        run: |
          python - <<EOF
          import re
          import requests
          import os
          
          # Fetch all tags from the repo to find the latest version
          api_url = "https://api.github.com/repos/KhronosGroup/Vulkan-Headers/tags"
          headers = {}
          
          # Use GitHub token if available (for higher rate limits)
          if 'GITHUB_TOKEN' in os.environ:
              headers['Authorization'] = f"token {os.environ['GITHUB_TOKEN']}"
          
          print(f"Fetching latest Vulkan-Headers version from {api_url}")
          response = requests.get(api_url, headers=headers)
          
          if response.status_code == 200:
              tags = response.json()
              # Find the latest SDK version tag
              sdk_tags = [tag for tag in tags if tag['name'].startswith('sdk-')]
              
              if not sdk_tags:
                  print("No SDK tags found, checking all tags")
                  # Try all tags if no sdk- prefix tags found
                  version_pattern = re.compile(r'v?(\d+\.\d+\.\d+)')
                  version_tags = []
                  
                  for tag in tags:
                      match = version_pattern.match(tag['name'])
                      if match:
                          version = match.group(1)
                          version_tags.append((version, tag['name']))
                  
                  if version_tags:
                      # Sort by version components to get the latest
                      latest_version = sorted(version_tags, key=lambda x: [int(n) for n in x[0].split('.')])[-1][0]
                  else:
                      print("No version tags found")
                      exit(1)
              else:
                  # Get the latest sdk tag
                  latest_tag = sdk_tags[0]['name']
                  latest_version = latest_tag.replace('sdk-', '')
                  print(f"Latest SDK tag: {latest_tag}")
              
              print(f"Latest version: {latest_version}")
              
              # Read current version from spec file
              spec_file = "vulkan-headers.spec"  # Adjust path as needed
              try:
                  with open(spec_file, 'r') as f:
                      spec_content = f.read()
              except FileNotFoundError:
                  print(f"Error: Spec file {spec_file} not found")
                  exit(1)
              
              # Extract current version
              current_version_match = re.search(r'Version:\s+"?(\d+\.\d+\.\d+)"?', spec_content)
              if current_version_match:
                  current_version = current_version_match.group(1)
                  print(f"Current version: {current_version}")
                  
                  # Check if update is needed
                  if current_version != latest_version:
                      print("Update needed!")
                      
                      # Update version in spec file
                      new_content = re.sub(r'(Version:\s+"?)(\d+\.\d+\.\d+)("?)', r'\g<1>' + latest_version + r'\g<3>', spec_content)
                      
                      with open(spec_file, 'w') as f:
                          f.write(new_content)
                      
                      # Set output for GitHub Actions
                      with open(os.environ['GITHUB_ENV'], 'a') as env_file:
                          env_file.write(f"UPDATED=true\n")
                          env_file.write(f"NEW_VERSION={latest_version}\n")
                  else:
                      print("No update needed")
                      with open(os.environ['GITHUB_ENV'], 'a') as env_file:
                          env_file.write("UPDATED=false\n")
              else:
                  print("Failed to extract current version")
          else:
              print(f"Failed to get latest version: {response.status_code}")
              print(f"Response: {response.text}")
          EOF
      
      - name: Commit changes if updated
        if: env.UPDATED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "vulkan-headers.spec"
          git commit -m "Update Vulkan Headers to version ${{ env.NEW_VERSION }}"
          git push
